= Applicazioni per ambienti intelligenti basati su MongoDB e sul protocollo CoAP
Marco Ieni <marcoieni94@gmail.com>
:toc-title: Indice
:toc: macro
:toclevels: 3
:stem:

toc::[]
:sectnums!:
[preface]
== Introduzione
L'obiettivo della tesi è la realizzazione di un sistema di monitoraggio e gestione di un ambiente intelligente. 
Gli utenti del sistema possono accedere ai servizi personalizzati e dinamici, che integrano i dati ambientali (provenienti da sensori) con le esigenze degli 
utenti, modificando le caratteristiche dell'ambiente stesso (tramite gli attuatori). Il sistema sviluppato sfrutta il protocollo CoAP come protocollo di 
comunicazione tra i dispositivi embedded (sensori ed attuatori) e immagazzina l'ingente quantità di dati che viene continuamente prodotta dai sensori per il 
monitoraggio ambientale nel Cloud, mediante il DBMS MongoDB.

Il lavoro della tesi è stato portato avanti in modo da fornire un'analisi ed un'implementazione delle tecnologie considerate, creando un sistema 
flessibile e funzionale per varie applicazioni.

Il servizio finale consente all’utente di:

* tenere sotto controllo i propri sensori, visualizzandone le misure effettuate nel tempo (anche applicando filtri come tag, gruppi o posizione);
* comandare i propri attuatori, stabilendo regole di funzionamento in base all'orario e alla locazione dell'interruttore attivato, accendendo solo determinate luci oppure caricando da remoto un proprio programma in python da eseguire ottenendo, così, dei servizi personalizzati;
* raggruppare i dispositivi in gruppi, in modo tale da avere una gestione più semplificata;
* rendere pubblici i propri dispositivi, in modo che tutti gli utenti registrati nel sistema possano accedervi;
* creare gruppi di utenti che hanno accesso solo a determinati gruppi di dispositivi. +
Per esemplificare, si pensi ad un'università in cui tutte le porte siano considerate degli attuatori collegati a uno strumento capace di identificare un utente (lettore di impronte digitali, tastierino numerico, card reader, ecc.). Si potrebbe abilitare a un gruppo di tirocinanti l’apertura di tutte le porte che conducono al laboratorio dove devono recarsi, in modo tale da farli accedere solamente a determinate zone e salvare l’orario di entrata e di uscita dal laboratorio di ogni tirocinante;
* ottenere informazioni in base alla posizione dei dispositivi. Ad esempio, è possibile ottenere una media della temperatura di un determinato luogo pesata in base alla precisione di ogni dispositivo a cui si ha accesso nelle vicinanze di un determinato punto, identificato da latitudine e longitudine.

Il presente lavoro si articola in quattro capitoli:

Capitolo 1 - Analisi delle tecnologie adoperate:: Nel primo capitolo vengono analizzati nel dettaglio:

* il protocollo CoAP, approfondendo anche il motivo per cui esso è di fondamentale importanza per la comunicazione dei sistemi embedded;
* analisi di soluzioni cloud-based, esaminandone vantaggi e svantaggi rispetto all’approccio centralizzato.
* MongoDB, descrivendo tutte le principali peculiarità di questa tipologia di database;

Capitolo 2 - Scelta dell'implementazione CoAP:: Nel secondo capitolo si riporta tutto il percorso che ha portato alla scelta dell'implementazione del CoAP da utilizzare, analizzando svantaggi, vantaggi e codici creati per ogni implementazione studiata.
Capitolo 3 - Il sistema sviluppato:: Nel terzo capitolo viene presentato il sistema sviluppato, analizzando lo scenario di riferimento e i vincoli che esso impone, lo schema del sistema e le sue funzionalità (anche mediante l’ausilio dei sequence diagram).
Capitolo 4 - Dettagli implementativi:: Nel quarto capitolo vengono illustrati alcuni screenshot della shell, che mostrano il funzionamento del sistema e i dettagli implementativi, come le query e le parti di codice più importanti e il diagramma delle classi principali.
Capitolo 5 - Sperimentazione:: Nel quinto capitolo viene mostrato un particolare scenario applicativo utilizzato per testare il sistema sviluppato.
In particolare, la sperimentazione è stata fatta ipotizzando un campus univeristario, ed implementando un servizio Smart Building Activity Based.
Tale servizio permette di controllare i consumi elettrici legati al riscaldamento dell'edificio del campus.

Sono inoltre presenti le conclusioni e la bibliografia.


:sectnums:

include::capitolo1.adoc[]

include::capitolo2.adoc[]

include::capitolo3.adoc[]

include::capitolo4.adoc[]

include::capitolo5.adoc[]

:sectnums!:
[glossary]
include::conclusione.adoc[]


[glossary]
== Glossario

[glossary]
Accesso a un dispositivo:: Per un sensore si intende leggere le misurazioni effettuate da esso mentre, per un attuatore, significa controllarlo.

server CoAP:: Server di frontiera di ogni sottorete

server remoto:: Server centrale, a cui fanno riferimento tutti i server CoAP

servizi utente:: Servizi che vengono creati dall'utente

servizi admin:: Servizi già presenti nel sistema

Disaster recovery:: L'insieme delle misure tecnologiche e logistico/organizzative atte a ripristinare sistemi, dati e infrastrutture necessarie all'erogazione di servizi di business per imprese, associazioni o enti, a fronte di gravi emergenze che ne intacchino la regolare attività footnote:[https://it.wikipedia.org/wiki/Disaster_recovery]

[bibliography]
== Bibliografia
- http://ieeexplore.ieee.org/xpl/articleDetails.jsp?tp=&arnumber=7057586
- Dharshan, "Understanding durability & write safety in MongoDB", 8/8/2014. http://blog.mongodirector.com/understanding-durability-write-safety-in-mongodb/
- https://it.wikipedia.org/wiki/MongoDB
- http://coap.technology
- Joe Weinman, "Defining a cloud", 18/01/2014. http://www.techradar.com/news/internet/cloud-services/defining-a-cloud-1209348
- [[joeweinman_website]] http://joeweinman.com
- Dan Allen. Seam in Action. Manning Publications. 2008.
- Peter Mell&#44; Timothy Grance, The NIST Definition of Cloud Computing. NIST&#44; Special Publication 800-145&#44 Settembre 2011.
- https://www.youtube.com/watch?v=nxrU3-7Ait4
- Joe Weinman, "Cloudonomics: A Rigorous Approach to Cloud Benefit Quantification", Ott 2011. https://www.csiac.org/sites/default/files/journal_files/stn14_4.pdf
